const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createRequire}=require('node:module');const req=createRequire(path.resolve(__dirname, '../package.json'));const ts=req('typescript');
const root=path.resolve(__dirname, '..');
function load(route,mocks={}){const module={exports:{}};const js=ts.transpileModule(fs.readFileSync(path.join(root,'src/app/api',route,'route.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('require','module','exports',js)(id=>mocks[id]??(id==='next/server'?{NextResponse:{json:(body,opts)=>({status:opts?.status??200,body})}}:req(id)),module,module.exports);return module.exports;}
test('notifications fail closed and only authorized requests reach sender',async()=>{
 let sends=0;const route=load('notifications/send',{'@/lib/notificationSender':{sendMiniAppNotification:async()=>{sends++;return {state:'success'}}},'@/lib/baseAppNotificationSender':{}});
 const request=key=>({headers:new Headers(key?{authorization:'Bearer '+key}:{}),json:async()=>({title:'Test',body:'Test',targetUrl:'https://example.org'})});
 const saved=process.env.NOTIFICATION_API_KEY;const base=process.env.BASE_APP_URL;
 try{delete process.env.NOTIFICATION_API_KEY;delete process.env.BASE_APP_URL;assert.equal((await route.POST(request())).status,503);process.env.NOTIFICATION_API_KEY='unit-test-key';assert.equal((await route.POST(request())).status,401);assert.equal((await route.POST(request('wrong'))).status,401);assert.equal(sends,0);assert.equal((await route.POST(request('unit-test-key'))).status,200);assert.equal(sends,1);}finally{if(saved===undefined)delete process.env.NOTIFICATION_API_KEY;else process.env.NOTIFICATION_API_KEY=saved;if(base===undefined)delete process.env.BASE_APP_URL;else process.env.BASE_APP_URL=base;}
});
test('metadata rejects arbitrary URLs without fetching and permits IPFS',async()=>{let fetches=0;const route=load('nft-metadata',{'@/lib/ipfs':{fetchIpfsJson:async()=>{fetches++;return {name:'NFT'}}}});for(const uri of ['https://example.org','http://127.0.0.1','file:///test'])assert.equal((await route.GET({nextUrl:new URL('https://app.test?uri='+encodeURIComponent(uri))})).status,400);assert.equal(fetches,0);assert.equal((await route.GET({nextUrl:new URL('https://app.test?uri=ipfs://test/metadata.json')})).status,200);assert.equal(fetches,1);});
test('swap provider exceptions never reach response bodies',async()=>{const saved=process.env.NEXT_PUBLIC_OBN_TOKEN;process.env.NEXT_PUBLIC_OBN_TOKEN='0x1111111111111111111111111111111111111111';try{const bad=async()=>{throw Error('SECRET_SENTINEL')};const mocks={'@coinbase/cdp-sdk':{CdpClient:class{evm={getSwapPrice:bad,createSwapQuote:bad}}}};const body={fromToken:'0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',toToken:process.env.NEXT_PUBLIC_OBN_TOKEN,fromAmount:'100',taker:'0x2222222222222222222222222222222222222222'};const responses=[await load('swap/price',mocks).GET({url:'https://app.test?'+new URLSearchParams(body)}),await load('swap/quote',mocks).POST({json:async()=>body})];for(const r of responses){assert.equal(r.status,502);assert.ok(!JSON.stringify(r.body).includes('SECRET_SENTINEL'));}}finally{if(saved===undefined)delete process.env.NEXT_PUBLIC_OBN_TOKEN;else process.env.NEXT_PUBLIC_OBN_TOKEN=saved;}});
